import type { TrackData } from '@/types'

export const curriculum: TrackData[] = [
  {
    id: 'dsa',
    title: 'Data Structures & Algorithms',
    description: 'Build unbreakable intuition for how data is organized and operated on — the foundation of all engineering.',
    icon: '🧮',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50',
    topics: [
      {
        id: 'dsa-foundations',
        trackId: 'dsa',
        title: 'Foundations',
        description: 'The mental models every engineer must internalize.',
        order: 1,
        concepts: [
          {
            id: 'big-o-notation',
            topicId: 'dsa-foundations',
            trackId: 'dsa',
            title: 'Big O Notation',
            description: 'Measure and compare the efficiency of algorithms without running them.',
            difficulty: 'beginner',
            order: 1,
            keyPoints: [
              'Time complexity describes how runtime grows relative to input size',
              'Space complexity describes how memory usage grows',
              'O(1) constant, O(log n) logarithmic, O(n) linear, O(n log n), O(n²) quadratic',
              'Drop constants and non-dominant terms when simplifying',
              'Best, average, and worst case are different — Big O typically describes worst case',
              'Amortized analysis handles operations that are occasionally expensive',
            ],
          },
          {
            id: 'recursion',
            topicId: 'dsa-foundations',
            trackId: 'dsa',
            title: 'Recursion & Iteration',
            description: 'Understand when to recurse, when to iterate, and the tradeoffs between them.',
            difficulty: 'beginner',
            order: 2,
            keyPoints: [
              'Every recursive call adds a frame to the call stack — O(n) space minimum',
              'Tail recursion can be optimized by compilers to O(1) space',
              'Base cases prevent infinite recursion',
              'Recursion excels for tree/graph problems; iteration often more space-efficient',
              'Memoization converts exponential recursive problems to polynomial',
            ],
          },
          {
            id: 'time-space-tradeoffs',
            topicId: 'dsa-foundations',
            trackId: 'dsa',
            title: 'Time vs Space Tradeoffs',
            description: 'The fundamental engineering tension: spend memory to save time, or vice versa.',
            difficulty: 'beginner',
            order: 3,
            keyPoints: [
              'Caching/memoization trades space for time',
              'In-place algorithms trade time for space',
              'Hash maps are the canonical O(1) time, O(n) space tradeoff tool',
              'Bit manipulation achieves O(1) space but sacrifices readability',
            ],
          },
        ],
      },
      {
        id: 'dsa-linear',
        trackId: 'dsa',
        title: 'Linear Data Structures',
        description: 'Arrays, lists, stacks, queues, and hash tables.',
        order: 2,
        concepts: [
          {
            id: 'arrays',
            topicId: 'dsa-linear',
            trackId: 'dsa',
            title: 'Arrays & Dynamic Arrays',
            description: 'Contiguous memory blocks and how dynamic resizing works.',
            difficulty: 'beginner',
            order: 1,
            keyPoints: [
              'Arrays store elements at contiguous memory addresses — O(1) index access',
              'Insertion/deletion at middle is O(n) due to shifting',
              'Dynamic arrays (ArrayList/list) double capacity when full — amortized O(1) append',
              'Two-pointer technique solves many O(n²) problems in O(n)',
              'Prefix sums enable O(1) range sum queries after O(n) preprocessing',
            ],
          },
          {
            id: 'linked-lists',
            topicId: 'dsa-linear',
            trackId: 'dsa',
            title: 'Linked Lists',
            description: 'Nodes connected by pointers — the opposite tradeoff to arrays.',
            difficulty: 'beginner',
            order: 2,
            keyPoints: [
              'O(1) insert/delete at known node; O(n) access by index',
              'Singly vs doubly linked: doubly allows O(1) deletion with node reference',
              'Fast-slow pointer (Floyd\'s cycle detection) detects cycles in O(n) time, O(1) space',
              'Reversing a linked list in-place is O(n) time, O(1) space',
              'Sentinel/dummy head nodes simplify edge cases',
            ],
          },
          {
            id: 'stacks-queues',
            topicId: 'dsa-linear',
            trackId: 'dsa',
            title: 'Stacks & Queues',
            description: 'LIFO and FIFO — the workhorses of algorithms.',
            difficulty: 'beginner',
            order: 3,
            keyPoints: [
              'Stack (LIFO): function call stack, DFS, balanced parentheses, monotonic stack',
              'Queue (FIFO): BFS, task scheduling, sliding window maximum',
              'Monotonic stack maintains elements in sorted order — O(n) for "next greater element"',
              'Deque (double-ended queue) enables O(1) operations at both ends',
            ],
            prerequisites: ['arrays', 'linked-lists'],
          },
          {
            id: 'hash-tables',
            topicId: 'dsa-linear',
            trackId: 'dsa',
            title: 'Hash Tables',
            description: 'The O(1) lookup that powers most optimized solutions.',
            difficulty: 'intermediate',
            order: 4,
            keyPoints: [
              'Hash function maps keys to array indices — collisions are inevitable',
              'Chaining vs open addressing for collision resolution',
              'Load factor determines when to resize (typically 0.7)',
              'Worst case O(n) with adversarial hash collisions; average O(1)',
              'Two Sum, frequency counting, anagram detection all use hash maps',
            ],
          },
        ],
      },
      {
        id: 'dsa-trees',
        trackId: 'dsa',
        title: 'Trees & Graphs',
        description: 'Hierarchical and relational data — the hardest and most important structures.',
        order: 3,
        concepts: [
          {
            id: 'binary-trees',
            topicId: 'dsa-trees',
            trackId: 'dsa',
            title: 'Binary Trees & BSTs',
            description: 'Hierarchical structures where every node has at most two children.',
            difficulty: 'intermediate',
            order: 1,
            keyPoints: [
              'Inorder traversal of BST yields sorted order',
              'Height-balanced trees (AVL, Red-Black) guarantee O(log n) operations',
              'DFS traversals: inorder, preorder, postorder',
              'BFS traversal uses a queue — gives level-by-level access',
              'BST operations (search, insert, delete) are O(h) where h = height',
            ],
            prerequisites: ['stacks-queues'],
          },
          {
            id: 'heaps',
            topicId: 'dsa-trees',
            trackId: 'dsa',
            title: 'Heaps & Priority Queues',
            description: 'Always-O(1) access to the min or max element.',
            difficulty: 'intermediate',
            order: 2,
            keyPoints: [
              'Heap property: parent is always ≤ (min-heap) or ≥ (max-heap) children',
              'Binary heap stored as array — parent at i, children at 2i+1 and 2i+2',
              'Heapify operation is O(n) — faster than inserting n elements one by one',
              'Heap sort is O(n log n) in-place',
              'k-th largest/smallest, merge k sorted lists, Dijkstra — all use heaps',
            ],
            prerequisites: ['binary-trees'],
          },
          {
            id: 'graphs',
            topicId: 'dsa-trees',
            trackId: 'dsa',
            title: 'Graphs & Traversals',
            description: 'The most general structure — trees are just constrained graphs.',
            difficulty: 'advanced',
            order: 3,
            keyPoints: [
              'Adjacency list vs adjacency matrix: O(V+E) vs O(V²) space',
              'BFS finds shortest path (unweighted graphs), explores level by level',
              'DFS explores as deep as possible — useful for cycle detection, topological sort',
              'Topological sort orders directed acyclic graph nodes by dependencies',
              'Union-Find (DSU) detects cycles and finds connected components in near-O(1)',
            ],
            prerequisites: ['binary-trees', 'stacks-queues'],
          },
          {
            id: 'shortest-paths',
            topicId: 'dsa-trees',
            trackId: 'dsa',
            title: 'Shortest Path Algorithms',
            description: "Dijkstra, Bellman-Ford, Floyd-Warshall — when to use each.",
            difficulty: 'advanced',
            order: 4,
            keyPoints: [
              "Dijkstra: O((V+E) log V) with min-heap, works only with non-negative weights",
              'Bellman-Ford: O(VE), handles negative weights, detects negative cycles',
              'Floyd-Warshall: O(V³) all-pairs shortest path via dynamic programming',
              "A*: Dijkstra + heuristic, faster in practice for known goal nodes",
            ],
            prerequisites: ['graphs', 'heaps'],
          },
        ],
      },
      {
        id: 'dsa-algorithms',
        trackId: 'dsa',
        title: 'Core Algorithms',
        description: 'The algorithmic patterns that appear in 80% of technical interviews and production code.',
        order: 4,
        concepts: [
          {
            id: 'sorting',
            topicId: 'dsa-algorithms',
            trackId: 'dsa',
            title: 'Sorting Algorithms',
            description: 'Deep understanding of how sorting works and when each algorithm wins.',
            difficulty: 'intermediate',
            order: 1,
            keyPoints: [
              'Comparison-based sorting lower bound: O(n log n)',
              'Merge sort: stable, O(n log n) always, O(n) extra space',
              'Quick sort: O(n log n) average, O(n²) worst case, O(log n) space',
              'Heap sort: O(n log n) always, O(1) space, not stable',
              'Counting/Radix sort: O(n) for bounded integer ranges',
              'Tim sort (Python/Java default): hybrid merge+insertion, stable',
            ],
          },
          {
            id: 'binary-search',
            topicId: 'dsa-algorithms',
            trackId: 'dsa',
            title: 'Binary Search & Variants',
            description: 'O(log n) search on any monotonic function, not just sorted arrays.',
            difficulty: 'intermediate',
            order: 2,
            keyPoints: [
              'Binary search works on any answer space with a monotonic predicate',
              'Off-by-one errors: when to use lo ≤ hi vs lo < hi',
              'Finding leftmost/rightmost occurrence requires careful boundary handling',
              '"Binary search the answer" technique: search for the optimal value directly',
              'Rotated sorted array, search in 2D matrix — key variants',
            ],
          },
          {
            id: 'dynamic-programming',
            topicId: 'dsa-algorithms',
            trackId: 'dsa',
            title: 'Dynamic Programming',
            description: 'Optimal substructure + overlapping subproblems = DP.',
            difficulty: 'advanced',
            order: 3,
            keyPoints: [
              'Two properties required: optimal substructure and overlapping subproblems',
              'Top-down (memoization) vs bottom-up (tabulation) — same complexity, different constants',
              'State definition is everything: what information do you need to make the decision?',
              'Classic patterns: 0/1 knapsack, LCS, LIS, coin change, edit distance',
              'Space optimization: many 2D DP tables reducible to 1D or even O(1)',
            ],
            prerequisites: ['recursion'],
          },
          {
            id: 'greedy-algorithms',
            topicId: 'dsa-algorithms',
            trackId: 'dsa',
            title: 'Greedy Algorithms',
            description: 'When locally optimal choices lead to globally optimal solutions.',
            difficulty: 'intermediate',
            order: 4,
            keyPoints: [
              'Greedy works when the problem has the greedy choice property',
              'Exchange argument: prove no swap of the greedy choice improves the solution',
              'Activity selection, Huffman coding, minimum spanning tree (Kruskal/Prim)',
              'Greedy fails when future choices depend on current — use DP instead',
            ],
            prerequisites: ['sorting'],
          },
          {
            id: 'sliding-window',
            topicId: 'dsa-algorithms',
            trackId: 'dsa',
            title: 'Two Pointers & Sliding Window',
            description: 'Reduce O(n²) brute force to O(n) with intelligent pointer movement.',
            difficulty: 'intermediate',
            order: 5,
            keyPoints: [
              'Two pointers work when moving pointers in one direction is always valid',
              'Sliding window maintains a valid window constraint as it expands/contracts',
              'Variable-size window: expand until invalid, shrink until valid',
              'Fixed-size window: add new element, remove old element',
              'Longest substring without repeating characters, minimum window substring — key problems',
            ],
            prerequisites: ['arrays', 'hash-tables'],
          },
        ],
      },
    ],
  },
  {
    id: 'ml',
    title: 'Machine Learning',
    description: 'From math foundations to neural networks — build the intuition that makes ML practitioners dangerous.',
    icon: '🧠',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50',
    topics: [
      {
        id: 'ml-math',
        trackId: 'ml',
        title: 'Math Foundations',
        description: 'The mathematical language of machine learning.',
        order: 1,
        concepts: [
          {
            id: 'linear-algebra-ml',
            topicId: 'ml-math',
            trackId: 'ml',
            title: 'Linear Algebra for ML',
            description: 'Vectors, matrices, and operations that power neural networks.',
            difficulty: 'beginner',
            order: 1,
            keyPoints: [
              'Vectors are directions and magnitudes in n-dimensional space',
              'Matrix multiplication is a composition of linear transformations',
              'Dot product measures similarity between vectors — basis of attention',
              'Eigenvalues/eigenvectors capture the "essence" of a transformation',
              'SVD decomposes any matrix — foundation of PCA and matrix factorization',
            ],
          },
          {
            id: 'calculus-ml',
            topicId: 'ml-math',
            trackId: 'ml',
            title: 'Calculus & Gradients',
            description: 'Derivatives tell us which direction to move to minimize loss.',
            difficulty: 'beginner',
            order: 2,
            keyPoints: [
              'Derivative = instantaneous rate of change = direction of steepest ascent',
              'Chain rule enables computing gradients through composed functions (backprop)',
              'Partial derivatives measure sensitivity to each parameter independently',
              'Gradient points in direction of steepest increase; we negate it to minimize',
              'Jacobian is the matrix of partial derivatives for vector-valued functions',
            ],
          },
          {
            id: 'probability-stats',
            topicId: 'ml-math',
            trackId: 'ml',
            title: 'Probability & Statistics',
            description: 'ML is fundamentally probabilistic — models predict distributions, not facts.',
            difficulty: 'beginner',
            order: 3,
            keyPoints: [
              'Conditional probability: P(A|B) = P(A∩B)/P(B)',
              'Bayes theorem: P(A|B) = P(B|A)P(A)/P(B) — posterior = likelihood × prior / evidence',
              'Expected value, variance, and distributions (Gaussian, Bernoulli, Categorical)',
              'MLE: find parameters that maximize likelihood of observed data',
              'KL divergence measures difference between two probability distributions',
            ],
          },
        ],
      },
      {
        id: 'ml-classical',
        trackId: 'ml',
        title: 'Classical ML',
        description: 'The algorithms that powered a decade of ML before deep learning.',
        order: 2,
        concepts: [
          {
            id: 'linear-regression',
            topicId: 'ml-classical',
            trackId: 'ml',
            title: 'Linear & Logistic Regression',
            description: 'The simplest models that illuminate the most fundamental ML concepts.',
            difficulty: 'beginner',
            order: 1,
            keyPoints: [
              'Linear regression: minimize MSE via normal equation or gradient descent',
              'Logistic regression: applies sigmoid to produce probabilities (0–1)',
              'Decision boundary is linear — logistic regression is a linear classifier',
              'L1 (Lasso) regularization induces sparsity; L2 (Ridge) shrinks weights',
              'Bias-variance tradeoff: underfitting vs overfitting',
            ],
            prerequisites: ['linear-algebra-ml', 'calculus-ml'],
          },
          {
            id: 'trees-ensembles',
            topicId: 'ml-classical',
            trackId: 'ml',
            title: 'Decision Trees & Ensembles',
            description: 'Combine weak learners to build powerful models (Random Forests, XGBoost).',
            difficulty: 'intermediate',
            order: 2,
            keyPoints: [
              'Decision trees split on features that maximize information gain (or minimize Gini)',
              'Bagging: train on bootstrap samples, reduce variance (Random Forests)',
              'Boosting: sequentially correct errors of weak learners (XGBoost, LightGBM)',
              'Gradient boosting fits new trees to residuals of previous ensemble',
              'Feature importance from trees measures average impurity decrease',
            ],
          },
          {
            id: 'model-evaluation',
            topicId: 'ml-classical',
            trackId: 'ml',
            title: 'Model Evaluation & Validation',
            description: 'How to know if your model actually works.',
            difficulty: 'intermediate',
            order: 3,
            keyPoints: [
              'Train/val/test split prevents information leakage from test set',
              'Cross-validation gives robust estimates with limited data',
              'Precision, recall, F1 — when accuracy is misleading (class imbalance)',
              'ROC-AUC measures discrimination ability across all thresholds',
              'Data leakage: when information from the future leaks into training',
            ],
          },
        ],
      },
      {
        id: 'ml-neural-nets',
        trackId: 'ml',
        title: 'Neural Networks',
        description: 'The architecture that scales to arbitrary complexity.',
        order: 3,
        concepts: [
          {
            id: 'mlp-backprop',
            topicId: 'ml-neural-nets',
            trackId: 'ml',
            title: 'MLPs & Backpropagation',
            description: 'How multi-layer networks learn through error signal propagation.',
            difficulty: 'intermediate',
            order: 1,
            keyPoints: [
              'Forward pass: compute predictions layer by layer',
              'Loss function measures prediction error (MSE, cross-entropy)',
              'Backpropagation applies chain rule to compute gradient w.r.t. all parameters',
              'Vanishing gradient problem: gradients shrink through deep networks',
              'Weight initialization matters: Xavier/He initialization prevents saturation',
            ],
            prerequisites: ['calculus-ml', 'linear-algebra-ml'],
          },
          {
            id: 'optimizers',
            topicId: 'ml-neural-nets',
            trackId: 'ml',
            title: 'Optimization & Optimizers',
            description: 'SGD, Adam, and the tricks that make training converge.',
            difficulty: 'intermediate',
            order: 2,
            keyPoints: [
              'SGD: update weights using gradient of single (mini-)batch',
              'Momentum: accumulate gradient history to escape local minima',
              'Adam: adaptive learning rates per parameter + momentum',
              'Learning rate scheduler: decay LR over training for fine convergence',
              'Gradient clipping prevents exploding gradients in deep/recurrent nets',
            ],
            prerequisites: ['mlp-backprop'],
          },
          {
            id: 'regularization',
            topicId: 'ml-neural-nets',
            trackId: 'ml',
            title: 'Regularization Techniques',
            description: 'Prevent overfitting and improve generalization.',
            difficulty: 'intermediate',
            order: 3,
            keyPoints: [
              'Dropout: randomly zero activations during training — implicit ensemble',
              'Batch normalization: normalize activations within each mini-batch',
              'Layer normalization: normalize across features (better for transformers)',
              'Data augmentation: increase effective dataset size via transformations',
              'Early stopping: stop training when validation loss stops improving',
            ],
            prerequisites: ['mlp-backprop'],
          },
        ],
      },
    ],
  },
  {
    id: 'ai-engineering',
    title: 'AI Engineering',
    description: 'Build production AI systems with LLMs — from transformers to RAG pipelines to evaluation.',
    icon: '⚡',
    color: 'text-orange-600',
    bgColor: 'bg-orange-50',
    topics: [
      {
        id: 'transformer-architecture',
        trackId: 'ai-engineering',
        title: 'Transformer Architecture',
        description: 'The architecture behind every modern LLM.',
        order: 1,
        concepts: [
          {
            id: 'attention-mechanism',
            topicId: 'transformer-architecture',
            trackId: 'ai-engineering',
            title: 'Attention Mechanism',
            description: "The core operation that lets transformers model arbitrary-range dependencies.",
            difficulty: 'intermediate',
            order: 1,
            keyPoints: [
              'Attention: weighted average of values, weights determined by query-key similarity',
              'Scaled dot-product attention: softmax(QKᵀ/√d_k)V',
              'Multi-head attention: run attention in parallel across multiple subspaces',
              'Causal masking prevents attending to future tokens (autoregressive generation)',
              'KV cache: store past keys/values to avoid recomputing during inference',
            ],
            prerequisites: ['linear-algebra-ml'],
          },
          {
            id: 'transformer-components',
            topicId: 'transformer-architecture',
            trackId: 'ai-engineering',
            title: 'Transformer Components',
            description: "Positional encoding, FFN layers, residual connections, and how they fit together.",
            difficulty: 'intermediate',
            order: 2,
            keyPoints: [
              'Positional encoding injects position information (learned or sinusoidal)',
              'Feed-forward layers apply non-linear transformation to each position independently',
              'Residual connections enable gradient flow in very deep networks',
              'Layer norm stabilizes training; pre-norm vs post-norm affects stability',
              'BERT is encoder-only (bidirectional); GPT is decoder-only (causal)',
            ],
            prerequisites: ['attention-mechanism'],
          },
          {
            id: 'tokenization',
            topicId: 'transformer-architecture',
            trackId: 'ai-engineering',
            title: 'Tokenization & Embeddings',
            description: 'How text becomes numbers — and why it matters for your prompts.',
            difficulty: 'beginner',
            order: 3,
            keyPoints: [
              'BPE (byte-pair encoding) learns vocabulary by iteratively merging frequent pairs',
              'Tokens ≠ words: "tokenization" may be 1–3 tokens depending on the model',
              'Token count directly determines context window usage and API cost',
              'Embeddings are dense vector representations of semantic meaning',
              'Word embeddings capture relationships: king - man + woman ≈ queen',
            ],
          },
        ],
      },
      {
        id: 'prompt-engineering',
        trackId: 'ai-engineering',
        title: 'Prompt Engineering',
        description: 'The craft of communicating with LLMs to get consistent, high-quality outputs.',
        order: 2,
        concepts: [
          {
            id: 'prompting-techniques',
            topicId: 'prompt-engineering',
            trackId: 'ai-engineering',
            title: 'Prompting Techniques',
            description: 'Zero-shot, few-shot, chain-of-thought, and beyond.',
            difficulty: 'beginner',
            order: 1,
            keyPoints: [
              'Zero-shot: task described in natural language, no examples',
              'Few-shot: include examples of input-output pairs in the prompt',
              'Chain-of-thought: ask the model to reason step by step before answering',
              'Self-consistency: sample multiple CoT paths, take majority vote',
              'System prompt sets persistent behavior; user prompt is the per-turn input',
            ],
          },
          {
            id: 'prompt-security',
            topicId: 'prompt-engineering',
            trackId: 'ai-engineering',
            title: 'Prompt Injection & Security',
            description: 'How adversarial inputs can hijack LLM behavior in production.',
            difficulty: 'intermediate',
            order: 2,
            keyPoints: [
              'Prompt injection: adversarial user input overrides system instructions',
              'Direct injection: user directly inputs malicious instructions',
              'Indirect injection: malicious content in retrieved documents (RAG poisoning)',
              'Defenses: input sanitization, output validation, sandboxing, least-privilege tools',
              'LLMs cannot reliably detect injection attempts — defense in depth required',
            ],
            prerequisites: ['prompting-techniques'],
          },
          {
            id: 'sampling-parameters',
            topicId: 'prompt-engineering',
            trackId: 'ai-engineering',
            title: 'Sampling & Model Parameters',
            description: 'Temperature, top-p, top-k — control randomness and quality.',
            difficulty: 'beginner',
            order: 3,
            keyPoints: [
              'Temperature scales the logit distribution: low → deterministic, high → creative',
              'Top-p (nucleus sampling): sample from smallest set of tokens summing to p',
              'Top-k: sample from k most likely tokens',
              'Temperature=0 for factual tasks; higher for creative tasks',
              'Max tokens limits output length; stop sequences end generation early',
            ],
          },
        ],
      },
      {
        id: 'rag-systems',
        trackId: 'ai-engineering',
        title: 'RAG & Vector Systems',
        description: 'Augment LLMs with external knowledge without fine-tuning.',
        order: 3,
        concepts: [
          {
            id: 'rag-fundamentals',
            topicId: 'rag-systems',
            trackId: 'ai-engineering',
            title: 'RAG Fundamentals',
            description: 'Retrieval-Augmented Generation: how, why, and when.',
            difficulty: 'intermediate',
            order: 1,
            keyPoints: [
              'RAG retrieves relevant documents at inference time and injects into context',
              'Three stages: indexing (embed documents), retrieval (embed query, find nearest), generation',
              'Reduces hallucination by grounding responses in retrieved evidence',
              'Chunking strategy critically affects retrieval quality',
              'Hybrid search combines dense (embedding) + sparse (BM25) retrieval',
            ],
          },
          {
            id: 'vector-databases',
            topicId: 'rag-systems',
            trackId: 'ai-engineering',
            title: 'Embeddings & Vector Databases',
            description: 'Store and search billions of embeddings at sub-millisecond latency.',
            difficulty: 'intermediate',
            order: 2,
            keyPoints: [
              'Approximate Nearest Neighbor (ANN) avoids O(n) brute-force search',
              'HNSW: hierarchical graph structure — best recall/speed tradeoff',
              'IVF: inverted file index clusters vectors for faster search',
              'Cosine similarity for direction; Euclidean for magnitude',
              'Embedding models: OpenAI ada-002, Cohere, BAAI/bge — quality varies significantly',
            ],
            prerequisites: ['rag-fundamentals'],
          },
          {
            id: 'agentic-systems',
            topicId: 'rag-systems',
            trackId: 'ai-engineering',
            title: 'Agents & Tool Use',
            description: 'LLMs that take actions, call tools, and plan across multiple steps.',
            difficulty: 'advanced',
            order: 3,
            keyPoints: [
              'Tool use: LLM generates structured calls; executor runs them and returns results',
              'ReAct pattern: Reason then Act in interleaved steps',
              'Multi-agent: specialized agents orchestrated by a planner agent',
              'Context management is the #1 challenge: what to keep, compress, or discard',
              'Reliability degrades with chain length — structured output + validation helps',
            ],
            prerequisites: ['rag-fundamentals', 'prompting-techniques'],
          },
        ],
      },
      {
        id: 'production-ai',
        trackId: 'ai-engineering',
        title: 'Production AI Systems',
        description: 'Evaluation, observability, and reliability for AI systems at scale.',
        order: 4,
        concepts: [
          {
            id: 'llm-evaluation',
            topicId: 'production-ai',
            trackId: 'ai-engineering',
            title: 'LLM Evaluation',
            description: 'How to measure whether your AI system actually works.',
            difficulty: 'intermediate',
            order: 1,
            keyPoints: [
              'Task-specific metrics: BLEU/ROUGE for summarization, exact-match for QA',
              'LLM-as-judge: use a stronger model to evaluate outputs (scales better than human)',
              'Evals must cover: correctness, groundedness, instruction-following, safety',
              'Golden dataset: curated human-labeled examples for regression testing',
              'A/B testing in production with careful assignment to avoid contamination',
            ],
          },
          {
            id: 'fine-tuning',
            topicId: 'production-ai',
            trackId: 'ai-engineering',
            title: 'Fine-Tuning & Alignment',
            description: 'Adapt base models to specific tasks and behaviors.',
            difficulty: 'advanced',
            order: 2,
            keyPoints: [
              'Full fine-tuning updates all parameters — expensive but maximally flexible',
              'LoRA: low-rank adapters inject trainable matrices into frozen model',
              'SFT (supervised fine-tuning) teaches format and style on demonstration data',
              'RLHF: human preference data trains a reward model that guides policy',
              'DPO (Direct Preference Optimization) skips the reward model training step',
            ],
            prerequisites: ['attention-mechanism', 'optimizers'],
          },
          {
            id: 'ai-observability',
            topicId: 'production-ai',
            trackId: 'ai-engineering',
            title: 'AI Observability & Cost',
            description: 'Monitor, debug, and optimize AI systems in production.',
            difficulty: 'intermediate',
            order: 3,
            keyPoints: [
              'Trace every LLM call: prompt, response, latency, token count, cost',
              'Prompt caching reduces cost for repeated prefixes (50-90% savings)',
              'Streaming responses improve perceived latency with identical total time',
              'Rate limiting and retry logic handle transient API failures gracefully',
              'Context window management: summarize vs truncate vs discard older context',
            ],
            prerequisites: ['llm-evaluation'],
          },
        ],
      },
    ],
  },
  {
    id: 'system-design',
    title: 'System Design',
    description: 'Design systems that scale from 1 to 100 million users — the craft of senior engineers.',
    icon: '🏗️',
    color: 'text-green-600',
    bgColor: 'bg-green-50',
    topics: [
      {
        id: 'sd-fundamentals',
        trackId: 'system-design',
        title: 'Distributed Systems Fundamentals',
        description: 'The building blocks of every scalable system.',
        order: 1,
        concepts: [
          {
            id: 'cap-theorem',
            topicId: 'sd-fundamentals',
            trackId: 'system-design',
            title: 'CAP Theorem & Consistency Models',
            description: 'Every distributed system must make tradeoffs between consistency, availability, and partition tolerance.',
            difficulty: 'intermediate',
            order: 1,
            keyPoints: [
              'CAP: you can only guarantee 2 of 3 during a network partition',
              'CP systems sacrifice availability: wait for consensus before responding',
              'AP systems sacrifice consistency: serve potentially stale data during partitions',
              'PACELC extends CAP: even without partitions, choose latency vs consistency',
              'Strong consistency = linearizability; eventual consistency = BASE (Basically Available, Soft-state, Eventually consistent)',
            ],
          },
          {
            id: 'scaling-strategies',
            topicId: 'sd-fundamentals',
            trackId: 'system-design',
            title: 'Scaling Strategies',
            description: 'Horizontal vs vertical, caching, sharding, and load balancing.',
            difficulty: 'intermediate',
            order: 2,
            keyPoints: [
              'Vertical scaling (bigger machine) is simpler but has a ceiling',
              'Horizontal scaling adds more machines — requires stateless services',
              'Caching layers: CDN → reverse proxy → application → database',
              'Database sharding distributes data across nodes; increases complexity',
              'Consistent hashing minimizes reshuffling when nodes are added/removed',
            ],
          },
          {
            id: 'databases-design',
            topicId: 'sd-fundamentals',
            trackId: 'system-design',
            title: 'Database Selection',
            description: 'When to choose SQL vs NoSQL, and which NoSQL flavor.',
            difficulty: 'intermediate',
            order: 3,
            keyPoints: [
              'SQL: ACID transactions, complex joins, strong schema — best for relational data',
              'Document DB (MongoDB): flexible schema, hierarchical data, poor for joins',
              'Column store (Cassandra): write-heavy workloads, time-series, high availability',
              'Key-value store (Redis): caching, sessions, leaderboards — O(1) operations',
              'Graph DB (Neo4j): social networks, recommendation engines, deeply connected data',
            ],
          },
        ],
      },
      {
        id: 'sd-ai-systems',
        trackId: 'system-design',
        title: 'AI System Design',
        description: 'Design ML pipelines and AI systems for production.',
        order: 2,
        concepts: [
          {
            id: 'ml-pipeline-design',
            topicId: 'sd-ai-systems',
            trackId: 'system-design',
            title: 'ML Pipeline Design',
            description: 'From raw data to deployed model — the full production ML lifecycle.',
            difficulty: 'advanced',
            order: 1,
            keyPoints: [
              'Feature store: centralized repository for reusable features, prevents training-serving skew',
              'Model registry: versioned model artifacts with metadata and lineage',
              'Online vs offline serving: batch prediction vs real-time inference',
              'Shadow deployment: run new model in shadow alongside production model',
              'Canary deployment: route small % of traffic to new model before full rollout',
            ],
            prerequisites: ['model-evaluation'],
          },
          {
            id: 'ab-testing',
            topicId: 'sd-ai-systems',
            trackId: 'system-design',
            title: 'A/B Testing & Experimentation',
            description: 'Measure the impact of AI changes with statistical rigor.',
            difficulty: 'intermediate',
            order: 2,
            keyPoints: [
              'Random assignment to treatment/control must be unbiased',
              'Sample size depends on effect size, significance level α, and power 1-β',
              'Multi-armed bandit trades off exploration vs exploitation dynamically',
              'CUPED (Controlled-experiment Using Pre-Experiment Data) reduces variance',
              'Network effects invalidate simple A/B tests in social/marketplace systems',
            ],
          },
        ],
      },
    ],
  },
]

export function getAllConcepts() {
  return curriculum.flatMap(track =>
    track.topics.flatMap(topic => topic.concepts)
  )
}

export function getConceptById(id: string) {
  return getAllConcepts().find(c => c.id === id) ?? null
}

export function getTopicById(id: string) {
  return curriculum.flatMap(t => t.topics).find(t => t.id === id) ?? null
}

export function getTrackById(id: string) {
  return curriculum.find(t => t.id === id) ?? null
}

export function getConceptsByTrack(trackId: string) {
  const track = getTrackById(trackId)
  if (!track) return []
  return track.topics.flatMap(t => t.concepts)
}
